# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidentdetail',
            old_name='latitude',
            new_name='lattitude',
        ),
    ]
