# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160621_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesinvolved',
            name='sr_no',
            field=models.IntegerField(default=0),
        ),
    ]
