# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_vehiclesinvolved_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentdetail',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.AccidentIdentification'),
        ),
        migrations.AddField(
            model_name='vehiclesinvolved',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.AccidentIdentification'),
        ),
        migrations.AddField(
            model_name='victimsinvolved',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.AccidentIdentification'),
        ),
    ]
