# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20160623_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimsinvolved',
            name='sr_no',
            field=models.IntegerField(default=0),
        ),
    ]
