# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_victimsinvolved_sr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentidentification',
            name='date_time',
        ),
        migrations.AddField(
            model_name='accidentidentification',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='accidentidentification',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
