# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20160629_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentidentification',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
