# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20160629_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentidentification',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
