# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20160629_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentidentification',
            name='date',
        ),
    ]
