# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_roadlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadlocation',
            name='road_id',
            field=models.IntegerField(),
        ),
    ]
