# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20160706_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_id', models.IntegerField(unique=True)),
                ('road_type', models.CharField(max_length=100)),
                ('road_name', models.CharField(max_length=200)),
                ('road_lanes', models.CharField(max_length=50)),
                ('road_oneway', models.CharField(max_length=50)),
            ],
        ),
    ]
